import { MDBCol, MDBRow, MDBContainer } from 'mdb-react-ui-kit';
import React from 'react';

export default function Business() {
  return (
    <>
      <header>
        <div
          className='p-5 text-center bg-image'
          style={{ backgroundImage: "url('https://mdbootstrap.com/img/new/slides/041.webp')", height: 400 }}
        >
          <div className='mask' style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}>
            <div className='d-flex justify-content-center align-items-center h-100'>
              <div className='text-white'>
                <h1 className='mb-3'>LET US TELL THE WORLD ABOUT YOUR BRAND</h1>
                <h4 className='mb-3'><hr />We make the business go BOOM by understanding your customer's need and sell your ideas</h4>
              </div>
            </div>
          </div>
        </div>
      </header>
      <MDBContainer className='pt-5'>
        <MDBRow>
          <MDBCol md='4' size="12">
            <h3 className="text-center p-4">WEB APP INTEGRATION</h3>
          </MDBCol>
          <MDBCol md='8' size="12">
            <h6 className="pt-4">Website is the center of the digital ecosystem. Promoting or developing your website for more potential prospects. </h6>
          </MDBCol>
        </MDBRow>
      </MDBContainer>
      <MDBContainer className='pt-5'>
        <MDBRow>
          <MDBCol md='4' size="12">
            <h3 className="text-center p-4">LEAD GENERATION</h3>
          </MDBCol>
          <MDBCol md='8' size="12">
            <h6 className="pt-4">Leading the way of your audience into potential prospects. Potential prospects are the source of being potential customers.<br />
              Lead is a person who has potentially interest in a company's product or service and every lead consists of information. There are basically three types of leads based on interest, enrichment and qualification. Interest based leads are of two types ie., inbound leads (those who have shown their interest by themselves) and outbound leads (leads generated by targeting strategies). Enrichment based leads are again of two types ie., non enriched leads (leads that are thin on information, mostly having one contact information) and enriched leads (leads that have additional information other than contact details, which can be used for multi-channel marketing). Lastly, qualification based leads are of three types ie., Marketing Qualified Leads (MQL) [Leads who are interested but not ready to communicate], Sales Qualified Leads (SQL) [leads having actual interest and are a step closer in becoming paying customers] and Product Qualified Leads (PQL) [leads who have taken actions for becoming paying customers].<br />
              Lead generation helps to allocate the resources to the right kind of targeted audience, building brand awareness by educating the leads, thus, leading to growth in revenue and competitive advantage in the market.</h6>
          </MDBCol>
        </MDBRow>
      </MDBContainer>
      <MDBContainer className='pt-5'>
        <MDBRow>
          <MDBCol md='4' size="12">
            <h3 className="text-center p-4">BUSINESS ANALYSIS</h3>
          </MDBCol>
          <MDBCol md='8' size="12">
            <h6 className="pt-4">Creating creative marketing strategies after analysing the needs of the brand. Planning the initiative by foresight and assessment of targeted audience. It's a formal approach for introducing and managing changes in the marketing strategies to check if the strategy is able to generate leads or not. In business analysis there is a need to identify the targeted audience as per the product/service and decide the type of strategies that are required to adopt for pinning their interests. This process involves everything from identifying strategies, defining those strategies to executing them and checking whether they are adding value to the marketing campaign. <br />
              Business analysis helps us to avoid unnecessary costs on campaigns, identify new opportunities and improve the method of marketing campaigns. There are a few techniques such as MOST (Mission, Objectives and Strategies), MosCow (Must or Should, Could or Would), CATWOE (Customers, Actors, Transformation Process, World View, Owner and Environmental), SWOT (Strength, Weakness, Opportunities and Threats) and so on.</h6>
          </MDBCol>
        </MDBRow>
      </MDBContainer>
      <MDBContainer className='pt-5'>
        <MDBRow>
          <MDBCol md='4' size="12">
            <h3 className="text-center p-4">DEVELOPMENT PREDICTION</h3>
          </MDBCol>
          <MDBCol md='8' size="12">
            <h6 className="pt-4">Predicting the progress after custom build marketing strategies, results in development prediction. Analyzing and forecasting future events is the main objective of development prediction. This model saves a lot of resources and time as it tries to avoid implying wrong marketing strategies. It's getting the most out of a predictive analytics solution and leveraging data to make insightful decisions.It helps to predict the growth response and allows us to plan our next steps that are required for the marketing campaign. Development prediction permits different strategy plannings to reach defined goals with assurance of having backup. Some of the prediction models are classification model (data is categorized into groups based on learnings from the historical data, clustering model (data separated into small groups based on similar attributes), forecast model (deals with metric value prediction, estimating numeric value for new data based on learnings from historical data), outliers model (oriented around anomalous data entries within a dataset as it can identify anomalous figures either by themselves or in conjunction with other numbers and categories), time series model (consists a sequence of data points captured, using time as the input parameter) and so on.</h6>
          </MDBCol>
        </MDBRow>
      </MDBContainer>
    </>
  );
}